### ISSUE TITLE
autoprotocol-node?

### ISSUE THREAD

**Issue by bmiles** [Autodesk/bionano-wetLabAccelerator#1]
Hey @larsxschneider how easy would it be to produce an NPM package of Node JS functions for generating vanilla autoprotocol from this repo?

**Comment by larsxschneider** [comment]
I am no expert for this repo. @PeterRJones can you help here?

**Comment by maxbates** [comment]
@bmiles It should be fairly straightforward. You'll want to look in `app/scripts/conversion/autoprotocol`. `fromAbstraction()` is the function responsible for actually converting 'omniprotocol' to Autoprotocol. There will be some functions from `app/scripts/omniprotocol` that are called as well (they are exposed on the window from relevant scripts, should be made explicit as dependencies in the `var` statements at top of each script), and `lodash` is used extensively.

If you do end up writing an NPM module to handle the conversion, would greatly appreciate a pull request :)
